#!/usr/bin/env bash

# usage:
#  $ curl https://raw.githubusercontent.com/sharow/archlinux-digitalocean/master/updater | sh -
#    ~~ snip ~~
#  $ systemctl reboot
#      and you get latest kernel
#

#
# based on https://www.youtube.com/watch?v=LHNPTvMwHPE
#

if [ $(id -u) -ne 0 ]; then
	echo "You must be root"
	exit 0
fi

# current kernel version check
case $(uname -r) in
	"3.8.4-1-ARCH")
		;;
	*) echo "Not supported version!";
		exit 0
		;;
esac

# update packages first
# and solve this: https://www.archlinux.org/news/binaries-move-to-usrbin-requiring-update-intervention/
pacman-key --refresh-keys
pacman-key --populate
pacman -Syy
pacman -S --noconfirm archlinux-keyring
pacman -R --noconfirm texinfo syslinux jfsutils ppl
pacman -Su --noconfirm --ignore filesystem,bash
pacman -S --noconfirm bash
pacman -Su --noconfirm
rm -f /boot/syslinux/syslinux.cfg.pacsave
mv -f /etc/mkinitcpio.conf.pacnew /etc/mkinitcpio.conf

# https://www.archlinux.org/news/deprecation-of-etcsysctlconf/
mv /etc/sysctl.conf.pacsave /etc/sysctl.d/99-sysctl.conf

# remove IgnorePkg from pacman.conf
sed -i 's/^IgnorePkg/#IgnorePkg/' /etc/pacman.conf

# for VirtIO
sed -i 's/^MODULES=""/MODULES="virtio virtio_blk virtio_pci virtio_net"/' /etc/mkinitcpio.conf

# update kernel
if [ "$LTS" == '1' ]; then
	echo "not supported yet"
	#pacman -Su --noconfirm linux-lts
	#pacman -Rc --noconfirm linux
	pacman -Su --noconfirm linux
else
	pacman -Su --noconfirm linux
fi

# ignore udev's ethN renaming.
# http://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/
ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules

# replace netcfg -> netctl
pacman -R --noconfirm netcfg
pacman -S --noconfirm netctl
IP_ADDR=$(ip addr | grep -A 2 'eth0:' | tail -n 1 | cut -c 10- | sed 's/\(.*\)\/.*/\1/')
GATEWAY=$(route | grep default | awk '{print $2}')
DNS="($(cat /etc/resolv.conf | awk '{printf("\"%s\" ", $2)}'))"
cat <<EOF > /etc/netctl/eth0
Interface=eth0
Connection=ethernet
IP=static
Address='$IP_ADDR/24'
Gateway='$GATEWAY'
DNS='$DNS'
EOF
systemctl enable netctl@eth0

# install kexec, remove sysvcompat
pacman -S --noconfirm kexec-tools
pacman -R --noconfirm systemd-sysvcompat

# add kexec-tools to HoldPkg
sed -i 's/^HoldPkg     = \(*\)/HoldPkg     = \1 kexec-tools/' /etc/pacman.conf

# init command
pushd /usr/sbin
cat <<EOF > init
#!/bin/sh
kexec --load /boot/vmlinuz-linux --initrd=/boot/initramfs-linux.img --append="root=LABEL=DOROOT init=/usr/lib/systemd/systemd" &&
mount -o ro,remount / &&
kexec -e
exec /usr/lib/systemd/systemd
EOF
chmod 755 init
popd

pacman -Scc --noconfirm

echo ''
echo 'update successful'
echo '>>> systemctl reboot'
