#!/usr/bin/env bash

# usage:
#  $ curl https://raw.githubusercontent.com/sharow/archlinux-digitalocean/master/updater | sh -
#    ~~ snip ~~
#  $ systemctl reboot
#      and yout get latest kernel
#

#
# based on https://www.youtube.com/watch?v=LHNPTvMwHPE
#

if [ $(id -u) -ne 0 ]; then
	echo "You must be root"
	exit 0
fi

# current kernel version check
KERNEL_VER=$(uname -r)
case "$KERNEL_VER" in
	"3.8.4-1-ARCH")
		;;
	*) echo "Not supported version!";
		exit 0
		;;
esac

# update packages first
# and solve this: https://www.archlinux.org/news/binaries-move-to-usrbin-requiring-update-intervention/
pacman-key --populate
pacman -Syy
pacman -Su --noconfirm --ignore filesystem,bash
pacman -S --noconfirm bash
pacman -Su --noconfirm

# https://www.archlinux.org/news/deprecation-of-etcsysctlconf/
mv /etc/sysctl.conf.pacsave /etc/sysctl.d/99-sysctl.conf

# remove IgnorePkg from pacman.conf
sed -i 's/^IgnorePkg/#IgnorePkg/' /etc/pacman.conf

# for VirtIO
sed -i 's/^MODULES=""/MODULES="virtio virtio_blk virtio_pci virtio_net"/' /etc/mkinitcpio.conf

# update kernel
if [ "$LTS" == '1' ]; then
	echo "not supported yet"
	#pacman -Su --noconfirm linux-lts
	#pacman -Rc --noconfirm linux
	pacman -Su --noconfirm linux
else
	pacman -Su --noconfirm linux
fi

# ignore udev's ethN renaming.
# http://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/
ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules

# boot hack
pacman -S --noconfirm kexec-tools
pacman -Rc --noconfirm systemd-sysvcompat
pacman -Scc --noconfirm

# add kexec-tools to HoldPkg
sed -i 's/^HoldPkg     = \(*\)/HoldPkg     = \1 kexec-tools/' /etc/pacman.conf

# init command
pushd /sbin
cat <<EOF > init
#!/bin/sh
kexec --load /boot/vmlinuz-linux --initrd=/boot/initramfs-linux.img --append="root=LABEL=DOROOT init=/usr/lib/systemd/systemd" &&
mount -o ro,remount / &&
kexec -e
exec /usr/lib/systemd/systemd
EOF
chmod 755 init
popd

echo ''
echo 'update successful'
echo '>>> systemctl reboot'
